# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9626b99c70b07f529a621ba4d30e7aaf02294d9cca77dd302119209560e68bb6a37b343eaa2f0ad7a42f65b30118f594e80b578f7f97d4e882f26efe950b67f3

test:
  secret_key_base: acc493c65db425fe622cb916a82b1819e90608ab47f6add59369bd71b7104c4cd506a383ab0ef8897975bae009d4a730f33fed1b139fc323b34bcb5a1291414e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
